[package]
name = "ccusdt_replay_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
ccusdt_exchange_sim = { path = "../exchange_sim" }
ccusdt_replay_core = { path = "../replay_core" }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

